version: "3"

services:
  flask_app_1:
    build:
      context: .
      dockerfile: dockerfile
  ports:
     - "9000:8000"
  volumes:
     - .:/app
  flask_app_2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8000"
    volumes:
      - .:/app